<!DOCTYPE html>
<html dir="ltr" lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="robots" content="noindex,nofollow,noarchive,nosnippet,noodp,notranslate,noimageindex,nocache" />
        <title>Welcome to Rade!</title>
        <link rel="shortcut icon" href="https://i.imgur.com/ky9oqct.png" type="image/png">
        <?php $hue = \random_int(0, 360); ?>
        <?php $darkColor = static fn (float $alpha = 1) => "hsla($hue, 20%, 45%, $alpha)"; ?>
        <?php $lightColor = static fn (float $alpha = 1) => "hsla($hue, 20%, 95%, $alpha)"; ?>
        <style>
            :root {
                --body-bg: <?php echo $lightColor() ?>;
                --text-color: <?php echo $darkColor() ?>;
                --content-bg: #fff;
            }
            body {
                color: var(--text-color);
                font-family: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
                line-height: 1.5;
                margin: 0;
            }
            .d-none { display: none; }
            strong { font-weight: 600; }
            article { background: var(--content-bg); padding: 32px 12px 0; }
            article h1 { font-size: 28px; margin: 0 0 4px; padding: 0 12px; }
            article h1 { line-height: 1.3; }
            article p.success { margin: 0 0 30px; padding: 0 12px; }
            article section { display: flex; justify-content: space-between; align-items: center; font-size: .875rem; color: #a0aec0; }
            article section div { display: flex; }
            article section .customize svg { height: 1.25rem; margin-left: 1rem; margin-top: -1px; }
            article section .customize a { margin-left: .25rem; color: inherit; }
            .links { margin: 32px 0; }
            .link { align-items: center; border-radius: 6px; display: flex; padding: 12px; position: relative; }
            .link:hover { background: <?php echo $lightColor() ?>; }
            .link:hover a { color: #2563eb; text-decoration: underline; }
            .link-icon { border-radius: 6px; display: inline-flex; margin-right: 18px; padding: 12px; }
            .link:hover .description { color: var(--text-color); }
            .link-icon svg { height: 24px; width: 24px; }
            .link-text a { color: inherit; font-weight: 600; text-decoration: none; }
            .link-text a::after { position: absolute; top: 0; right: 0; bottom: 0; left: 0; z-index: 1; pointer-events: auto; content: ''; }
            .link-text p.description { color: #64748b; font-size: 14px; margin: 0; }
            .link-blue .link-icon { background: #eff6ff; color: #3b82f6; }
            .link-blue:hover .link-icon { outline: 2px solid #3b82f6; outline-offset: -2px; }
            .link-green .link-icon { background: #f0fdf4; color: #22c55e; }
            .link-green:hover .link-icon { outline: 2px solid #22c55e; outline-offset: -2px; }
            .link-red .link-icon { background: #fef2f2; color: #ef4444; }
            .link-red:hover .link-icon { outline: 2px solid #ef4444; outline-offset: -2px; }
            .link-yellow .link-icon { background: #fffbeb; color: #f59e0b; }
            .link-yellow:hover .link-icon { outline: 2px solid #f59e0b; outline-offset: -2px; }
            @media (min-width: 768px) {
                body { background: var(--body-bg); min-height: 100vh; display: flex; flex-direction: column; justify-content: center; }
                article { border-radius: 24px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1); margin: 40px auto; max-width: 700px; padding: 48px 88px; }
                article h1 { font-size: 36px; padding: 0; }
                article p.success { font-size: 18px; padding: 0; }
                article section { margin-top: -1rem; font-size: 1rem; }
                .md\:inline-block { display: inline-block; }
                .link { padding: 12px 18px; }
                .link-icon svg { height: 32px; width: 32px; }
                .link-text a { font-size: 17px; }
                .link-text p.description { font-size: 15px; }
            }
        </style>
    </head>
    <body>
        <article>
            <h1>Welcome to PHP Rade</h1>
            <p class="success">You have <strong>successfully installed PHP Rade</strong> in your application.</p>
            <p>You're seeing this page because you haven't configured any homepage URL<?php echo $debug ? ', and <strong>debug</strong> mode is enabled.' : '.'; ?></p>
            <div class="links">
                <div class="link link-blue">
                    <div class="link-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                        </svg>
                    </div>
                    <div class="link-text">
                        <a href="https://docs.divinenii.com/php/rade/index.html" target="_blank">Read PHP Rade Docs</a>
                        <p class="description">Learn how to use PHP Rade to fit your needs.</p>
                    </div>
                </div>

                <div class="link link-red">
                    <div class="link-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                        </svg>
                    </div>
                    <div class="link-text">
                        <a href="https://divinenii.com/sponsor" target="_blank">Sponsor PHP Rade</a>
                        <p class="description">Fund the development of new features. <span class="d-none md:inline-block">One-time or regular donations</span></p>
                    </div>
                </div>

                <div class="link link-yellow">
                    <div class="link-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
                        </svg>
                    </div>
                    <div class="link-text">
                        <a href="https://github.com/divineniiquaye/php-rade/stargazers" target="_blank">Star PHP Rade on GitHub</a>
                        <p class="description">Help us promote PHP Rade to reach new developers</p>
                    </div>
                </div>
            </div>
            <section>
                <div class="customize">
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="ml-4 -mt-px w-5 h-5 text-gray-400">
                        <path d="M22 2v20h-20v-20h20zm2-2h-24v24h24v-24zm-4 7h-8v1h8v-1zm0 5h-8v1h8v-1zm0 5h-8v1h8v-1zm-10.516-11.304l-.71-.696-2.553 2.607-1.539-1.452-.698.71 2.25 2.135 3.25-3.304zm0 5l-.71-.696-2.552 2.607-1.539-1.452-.698.709 2.249 2.136 3.25-3.304zm0 5l-.71-.696-2.552 2.607-1.539-1.452-.698.709 2.249 2.136 3.25-3.304z"/>
                    </svg>
                    <a href="https://github.com/divineniiquaye/php-rade/blob/master/CHANGELOG.md">See the CHANGELOG</a>
                    <span class="d-none md:inline-block">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="ml-4 -mt-px w-5 h-5 text-gray-400">
                            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
                        </svg>
                        <a href="https://github.com/divineniiquaye/php-rade/issues" class="ml-1 underline">Report issues</a>
                    </span>
                </div>
                <div>Rade v<?php echo $version; ?> (PHP v<?php echo \PHP_VERSION; ?>)</div>
            </section>
        </article>
    </body>
</html>
