<?php

declare(strict_types=1);

/*
 * This file is part of DivineNii opensource projects.
 *
 * PHP version 7.4 and above required
 *
 * @author    Divine Niiquaye Ibok <divineibok@gmail.com>
 * @copyright 2019 DivineNii (https://divinenii.com/)
 * @license   https://opensource.org/licenses/BSD-3-Clause License
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Rade\Debug\Tracy;

use Tracy\Dumper;
use Tracy\Helpers;

?>
<style class="tracy-debug">
	#tracy-debug .nette-ContainerPanel table {
		width: 100%;
		white-space: nowrap;
	}

	#tracy-debug .nette-ContainerPanel .created {
		font-weight: bold;
	}

	#tracy-debug .nette-ContainerPanel .yes {
		color: green;
		font-weight: bold;
	}

	#tracy-debug .nette-ContainerPanel table pre {
		display: inline;
		background: transparent;
	}
</style>

<h1><?= \get_class($this->container) ?></h1>

<div class="tracy-inner nette-ContainerPanel">
<div class="tracy-inner-container">
    <h2>Services</h2>

    <table class="tracy-sortable">
		<thead>
		<tr>
			<th>Name</th>
			<th>Autowired</th>
			<th>Initialized</th>
			<th>Service</th>
		</tr>
		</thead>
		<tbody>
        <?php foreach ($instances as $id => $service): ?>
            <tr>
                <td class="<?= isset($services[$id]) ? 'created' : ''; ?>">
                    <?= \is_numeric($id) ? "<span title='$id'>–</span>" : Helpers::escapeHtml($id) ?>
                </td>
                <td class="<?= isset($types[$id]) ? 'yes' : ''; ?>"><?= isset($types[$id]) ? 'yes' : 'no'; ?></td>
                <td class="<?= $this->container->initialized($id) ? 'yes' : ''; ?>"><?= $this->container->initialized($id) ? 'yes' : 'no'; ?></td>
                <td>
                    <?php if (isset($services[$id])): ?>
                        <?= Dumper::toHtml($services[$id] ?? $service, [Dumper::COLLAPSE => true, Dumper::LIVE => true]); ?>
                    <?php else: ?>
                        <code><?= Dumper::toHtml($service); ?></code>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach ?>
		</tbody>
	</table>

	<h2>Configurations</h2>

	<div class="nette-ContainerPanel-parameters">
		<?= Dumper::toHtml($configs); ?>
	</div>

	<p>Source: <?= Helpers::editorLink($file) ?></p>
</div>
</div>
